name: debates_analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - jupyterlab
  - nltk
  - spacy
  - tqdm
  - requests
  - openpyxl # for reading .xlsx files
  - pip
  - pip:
    - wordcloud
    - textblob
    - xlrd
    - networkx
    - pycountry
    - torch
    - transformers
    - gensim
    - vaderSentiment